---
- name: Ensure restic directories exist
  ansible.builtin.file:
    state: 'directory'
    path: '{{ item }}'
    mode: '0755'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
  with_items: '{{ restic_create_paths }}'

- name: Check if downloaded binary is present
  ansible.builtin.stat:
    path: '{{ restic_download_path }}/bin/restic-{{ restic_version }}'
  register: restic_executable

- name: Check if installed binary is present
  ansible.builtin.stat:
    path: '{{ restic_install_path }}/restic'
  register: restic_installed
