---
# tasks file for skeleton

- name: Create backup script
  template:
    src: restic_script.j2
    dest: '{{ restic_script_dir }}/backup-{{ item.name }}.sh'
    mode: '0700'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
  no_log: True
  with_items: '{{ restic_backups }}'
  when:
    - item.name is defined
    - item.src is defined or item.stdin is defined and item.stdin == true and item.stdin_cmd is defined
    - item.repo in restic_repos